# Jekyll Configs
layouts: ./_layouts
exclude: [readme.md]
host: localhost
port: 4000

pygments: true
#Permalink
permalink: pretty

baseurl: http://wvus-ibu.github.io/wvus.uikit
developerdocs: /snippets
designerdocs: /designer

# vars
repo: https://github.com/wvus-ibu/wvus.uikit
issues: https://github.com/wvus-ibu/wvus.uikit/issues?state=open
changelog: https://github.com/wvus-ibu/wvus.uikit/releases
download: https://github.com/wvus-ibu/wvus.uikit/releases/download/v1.1.2/wvus.uikit-1.1.2.zip
bootstrap: http://getbootstrap.com/
font-awesome: http://fontawesome.io/
