pygments: true
#Permalink
permalink: pretty

baseurl: http://wvus-ibu.github.io/wvus.uikit


# vars
repo: https://github.com/wvus-ibu/wvus.uikit
download: https://github.com/wvus-ibu/wvus.uikit/archive/v0.4.zip